
["General Settings"]
	#Prints additional debug information to the log.
	#In most cases this information isn't necessary and excessive debugging can generate lag.
	#However, if you are troubleshooting or reporting an issue, advanced log info may be helpful to turn on.
	advanced_debugging = false

